backend:
  name: git-gateway

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "/images/uploads"

locale: "zh_Hans"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "文章" # Used in the UI, ie.: "New Post"
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "标题", name: "title", widget: "string" }
      - { label: "作者", name: "author", widget: "string", default: "解恪布" }
      - { label: "发布时间", name: "date", widget: "datetime" }
      - { label: "标签", name: "tags", widget: "list", default: ["news"] }
      - {
          label: "文章简介",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "正文", name: "body", widget: "markdown" }
  - name: "pages"
    label: "其它页面"
    files:
      - file: "content/about.md"
        label: "关于"
        name: "about"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "发布时间", name: "date", widget: "datetime" }
          - { label: "Slug", name: "slug", widget: "hideen", default: "about" }
          - {
              label: "文章简介",
              name: "description",
              widget: "string",
              required: false,
            }
          - { label: "正文", name: "body", widget: "markdown" }
